"""Freshness check prompt template.

Ported from the n8n theme generation subworkflow where the selected
theme is checked against recent newsletters for editorial freshness
and repetition.

The LLM compares the proposed theme against recent newsletters at
is2digital.com/newsletters and reports whether content is repetitive,
with suggested changes.

Model: ``LLM_FRESHNESS_CHECK_MODEL`` (``google/gemini-2.5-flash`` via
OpenRouter).
"""

from __future__ import annotations

from ica.llm_configs import get_process_prompts


def build_freshness_check_prompt(
    theme_body: str,
) -> tuple[str, str]:
    """Build the system and user messages for the freshness check.

    Loads the system and instruction prompts from the ``freshness-check``
    JSON config via :func:`~ica.llm_configs.get_process_prompts`.

    Args:
        theme_body: The full theme body text generated by the theme
            generation step (the raw block for the selected theme).

    Returns:
        A ``(system_prompt, user_prompt)`` tuple ready to pass to the LLM.
    """
    system_prompt, instruction = get_process_prompts("freshness-check")

    user_prompt = instruction.format(
        theme_body=theme_body,
    )

    return system_prompt, user_prompt
