"""Freshness check prompt template.

Ported from the n8n theme generation subworkflow where the selected
theme is checked against recent newsletters for editorial freshness
and repetition.

The LLM compares the proposed theme against recent newsletters at
is2digital.com/newsletters and reports whether content is repetitive,
with suggested changes.

Model: ``LLM_FRESHNESS_CHECK_MODEL`` (``google/gemini-2.5-flash`` via
OpenRouter).
"""

from __future__ import annotations

FRESHNESS_CHECK_PROMPT = """\
I have created a text theme for my new newsletter, \
please, check editorial freshness and if it's not repetitive to last \
newsletters,

I will provide the text theme text and a link to site where you can \
find recent newsletters

The text theme:
{theme_body}

Links to my site, on that page, you can find links to recent \
newsletters, one 3 most recent, and check against them:
https://www.is2digital.com/newsletters

As final output - give your results for this task as a structured \
output, and tell what to change if needed, try to explain why\
"""


def build_freshness_check_prompt(
    theme_body: str,
) -> tuple[str, str]:
    """Build the system and user messages for the freshness check.

    The freshness check compares a proposed newsletter theme against
    the most recent published newsletters to detect repetition and
    suggest changes.

    Args:
        theme_body: The full theme body text generated by the theme
            generation step (the raw block for the selected theme).

    Returns:
        A ``(system_prompt, user_prompt)`` tuple ready to pass to the LLM.
        The system prompt is a brief role description; the user prompt
        contains the full freshness check instructions.
    """
    system_prompt = (
        "You are a newsletter editorial assistant. Your job is to "
        "evaluate whether a proposed newsletter theme is fresh and "
        "non-repetitive compared to recently published newsletters."
    )

    user_prompt = FRESHNESS_CHECK_PROMPT.format(
        theme_body=theme_body,
    )

    return system_prompt, user_prompt
