"""SQLAlchemy 2.0 ORM models for all database tables.

Schema matches PRD Section 2.2. The database ``n8n_custom_data`` contains:

- ``articles`` — discovered articles with editorial metadata (type discriminator)
- ``themes`` — generated themes with approval status (type discriminator)
- ``notes`` — consolidated feedback/learning data with type discriminator
"""

from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import Boolean, Date, Index, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""


# ---------------------------------------------------------------------------
# articles
# ---------------------------------------------------------------------------


class Article(Base):
    """An article discovered by the collection pipeline.

    The ``type`` column acts as a discriminator: ``'curated'`` (default) for
    articles sourced from the collection utility, ``'curated'`` updated during
    summarization data prep (PRD Section 3.2).
    """

    __tablename__ = "articles"

    url: Mapped[str] = mapped_column(Text, primary_key=True)
    title: Mapped[str | None] = mapped_column(Text)
    origin: Mapped[str | None] = mapped_column(Text)
    publish_date: Mapped[date | None] = mapped_column(Date)
    approved: Mapped[bool | None] = mapped_column(Boolean)
    industry_news: Mapped[bool | None] = mapped_column(Boolean)
    newsletter_id: Mapped[str | None] = mapped_column(Text)
    type: Mapped[str] = mapped_column(
        String(50), nullable=False, server_default="curated",
    )
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())


# ---------------------------------------------------------------------------
# themes
# ---------------------------------------------------------------------------


class Theme(Base):
    """A generated theme.

    The ``type`` column acts as a discriminator: ``'newsletter'`` (default)
    for themes generated by the newsletter pipeline.
    """

    __tablename__ = "themes"

    theme: Mapped[str] = mapped_column(Text, primary_key=True)
    theme_body: Mapped[str | None] = mapped_column(Text)
    theme_summary: Mapped[str | None] = mapped_column(Text)
    newsletter_id: Mapped[str | None] = mapped_column(Text)
    approved: Mapped[bool | None] = mapped_column(Boolean)
    type: Mapped[str] = mapped_column(
        String(50), nullable=False, server_default="newsletter",
    )
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())


# ---------------------------------------------------------------------------
# notes (consolidated feedback / learning data)
# ---------------------------------------------------------------------------


class Note(Base):
    """Consolidated feedback and learning data.

    Replaces the former per-pipeline feedback tables.  The ``type`` column
    acts as a discriminator:

    - ``user_summarization`` — feedback on article summarization quality
    - ``user_newsletter_themes`` — feedback on theme generation
    - ``user_markdowngenerator`` — feedback on markdown generation
    - ``user_htmlgenerator`` — feedback on HTML generation
    - ``user_email_subject`` — feedback on email subject line generation
    """

    __tablename__ = "notes"

    id: Mapped[int] = mapped_column(primary_key=True)
    feedback_text: Mapped[str] = mapped_column(Text, nullable=False)
    type: Mapped[str] = mapped_column(String(50), nullable=False)
    newsletter_id: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    __table_args__ = (
        Index("ix_notes_created_at", "created_at"),
        Index("ix_notes_type_created_at", "type", "created_at"),
    )
